### ISSUE TITLE
2023c update: C.8.34.5 Photoacoustic Functional Group Macros

### ISSUE THREAD

**Issue by celeron533** [innolitics/dicom-standard#93]
The dictionary does not contain a new Dicom Macro definition when parsing the DicomDoc.

https://dicom.nema.org/medical/dicom/2023c/output/chtml/part03/sect_C.8.34.5.4.html

```
PYTHONPATH=.. python3 postprocess_integrate_func_group_macros.py tmp/module_to_attributes_no_duplicates.json dist/macros.json dist/ciod_to_func_group_macros.json dist/macro_to_attributes.json > dist/module_to_attributes.json
Traceback (most recent call last):
  File "postprocess_integrate_func_group_macros.py", line 89, in <module>
    new_attributes = process_ciod_specific_attributes(module_to_attributes, macros, ciod_to_macro, macro_to_attributes)
  File "postprocess_integrate_func_group_macros.py", line 66, in process_ciod_specific_attributes
    rel['macroName'] = macro_dict[rel['macroId']]['name']
KeyError: 'photoacoustic-reconstruction-algorithm-attributes'
make: *** [Makefile:47: dist/module_to_attributes.json] Error 1
make: *** Deleting file 'dist/module_to_attributes.json'
```

possibly caused by:
`extract_modules_macros_with_attributes.py`
The macro table name is 'Photoacoustic Excitation Characteristics Attributes', which is not following the normal format
https://dicom.nema.org/medical/dicom/2023c/output/html/part03.html#table_C.8.34.5.1-1

Current regex to identify if this is a Table and Macro Table:
```python
TABLE_SUFFIX = re.compile("(.*Module Attributes$)|(.*Module Table$)|(.*Macro Attributes$)|(.*Macro Attributes Description$)")
MACRO_TABLE_SUFFIX = re.compile("(.*Macro Attributes$)|(.*Macro Attributes Description$)")
```

**Comment by celeron533** [comment]
This issue no longer exists with latest code and 2024a
